export const DATABASE_ID = 'main'
export const DEFAULT_DATA_ENDPOINT = 'http://localhost:9876'
export const DEFAULT_DEMO_TOKEN = 'sirannon-demo-token'
export const WAREHOUSE_DEMO_TOKEN = 'sirannon-warehouse-token'
export const WEBSOCKET_AUTH_PROTOCOL_PREFIX = 'sirannon.demo.auth.'
